/**
 * The HTML, as functions returning strings.
 *
 * No template engine and no JSX: an htmx application's views are small, and
 * each route's answer is the markup it sends. Anything that arrived from the
 * user (a name, a tip query) goes through `escape` first.
 */

const escapes: Record<string, string> = {
  "&": "&amp;",
  "<": "&lt;",
  ">": "&gt;",
  '"': "&quot;",
  "'": "&#39;",
};

/** Escape a value that came from outside the program before putting it in HTML. */
export function escape(value: string): string {
  return value.replace(/[&<>"']/g, (char) => escapes[char] ?? char);
}

/** The greeting card. `name` is already escaped. */
export function greeting(name: string): string {
  return `
<div class="flex flex-col gap-4">
  <span class="size-2.5 rounded-full bg-emerald-400" aria-hidden="true"></span>
  <h1 class="text-3xl font-semibold">Welcome, ${name}! 👋</h1>
  <p class="text-dim">Your Vantail window is ready. It is rendered by Hono, styled with Tailwind, and driven by htmx - no JSX in sight.</p>
  <div class="mt-2 flex items-center gap-2">
    <button
      type="button"
      class="rounded-lg bg-accent px-3 py-1.5 text-sm font-medium text-white hover:opacity-90"
      hx-get="/tip"
      hx-target="#greeting"
      hx-swap="innerHTML"
    >Another tip</button>
  </div>
</div>`;
}

/** A rotating tip, swapped back into the greeting card by htmx. */
export function tip(index: number): string {
  const tips = [
    "Vantail gives your web page a native window, dialogs and scoped filesystem access.",
    "There is no Node.js or localhost server in a packaged Vantail app.",
    "htmx swaps server-rendered HTML into the page - the server stays the source of truth.",
    "Tailwind is generated by Vite in this project, with a small custom palette.",
    "Permissions start empty; each native capability is opted into in vantail.config.ts.",
  ];
  const text = tips[index % tips.length] ?? tips[0]!;
  return `
<div class="flex flex-col gap-4">
  <span class="size-2.5 rounded-full bg-emerald-400" aria-hidden="true"></span>
  <h1 class="text-3xl font-semibold">Hello again! ✨</h1>
  <p class="text-dim">${escape(text)}</p>
</div>`;
}
